# Display Dataframe as Table

* [Show DataFrame as table in iPython Notebook](https://stackoverflow.com/a/29665452/4281353)

In [15]:
import numpy as np
import pandas as pd
from IPython.display import (
    display,
    HTML,
)

In [9]:
df = pd.read_json(
    "./data/recovery.json",
    dtype={
        "facility": pd.CategoricalDtype(), # Must specify a class instance (https://stackoverflow.com/questions/75089569)
        "supplier": pd.CategoricalDtype(),
        "supplierCode": pd.CategoricalDtype(),
        "suppliedM3": np.float32,
        "recoveredM3": np.float32,
    },
    convert_dates=['date']
)

In [10]:
DEBUG: bool = True

In [11]:
if DEBUG:
    display(df)

,facility,timeStart,processTime,supplier,suppliedM3,recoveredM3,date,timeEnd,supplierCode
0,Bundaberg,9/1/22 8:16 AM,4:05,Mary,5.09,4.13,NaT,NaN,NaN
1,Newcastle,8:29:00 AM,NaN,NaN,2.00,1.55,2022-09-01,9:07:00 AM,har
2,Newcastle,9:27:00 AM,NaN,NaN,6.80,4.15,2022-09-01,11:28:00 AM,dic
3,Newcastle,11:38:00 AM,NaN,NaN,1.95,1.55,2022-09-01,12:21:00 PM,har
4,Bundaberg,9/1/22 12:34 PM,1:50,Mary Therese,3.78,2.56,NaT,NaN,NaN
...,...,...,...,...,...,...,...,...,...
227,Newcastle,11:40:00 AM,NaN,NaN,3.70,2.35,2022-09-30,12:41:00 PM,tom
228,Newcastle,12:52:00 PM,NaN,NaN,6.35,4.55,2022-09-30,2:36:00 PM,dic
229,Bundaberg,9/30/22 1:48 PM,3:40,Mary Therese,4.53,2.73,NaT,NaN,NaN
230,Newcastle,3:02:00 PM,NaN,NaN,2.00,1.45,2022-09-30,3:42:00 PM,har
231,Newcastle,4:02:00 PM,NaN,NaN,6.30,3.90,2022-09-30,6:27:00 PM,dic

In [16]:
if DEBUG:
    display(HTML(df.to_html()))