* [Selecting/excluding sets of columns in pandas](https://stackoverflow.com/a/51601986/4281353)

In [1]:
import numpy as np
import pandas as pd

# Create a dataframe with columns A,B,C and D
df = pd.DataFrame(np.random.randn(100, 4), columns=list('ABCD'))

# include the columns you want
df[df.columns[df.columns.isin(['A', 'B'])]]

# or more simply include columns:
df[['A', 'B']]

# exclude columns you don't want
df[df.columns[~df.columns.isin(['C','D'])]]

# or even simpler since 0.24
# with the caveat that it reorders columns alphabetically 
df[df.columns.difference(['C', 'D'])]

           A         B
0  -1.389901  0.355966
1  -0.335859 -1.081798
2   0.000856  0.863560
3  -1.073584  1.606143
4  -1.236630 -1.081519
..       ...       ...
95 -0.101795  1.018276
96 -0.002801 -0.716710
97 -1.284928  0.633800
98 -1.074113  0.553467
99 -1.619629  1.013547

[100 rows x 2 columns]